# Generated by Django 3.1.2 on 2021-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_column='IP地址', max_length=30)),
                ('computerName', models.CharField(db_column='计算机名称', max_length=30)),
                ('numberOfProcess', models.CharField(db_column='进程数', max_length=5)),
                ('oS', models.CharField(db_column='操作系统', max_length=10)),
                ('path', models.CharField(db_column='路径', max_length=100)),
                ('processorArchitecture', models.CharField(db_column='处理器的位数', max_length=10)),
                ('processorIdentifier', models.CharField(db_column='处理器的配置信息', max_length=50)),
                ('userName', models.CharField(db_column='客户端的用户名', max_length=20)),
                ('userProfile', models.CharField(db_column='客户端的用户文件路径', max_length=100)),
                ('userAgent', models.CharField(db_column='请求头', max_length=200)),
                ('httpRefer', models.CharField(db_column='跳转的网页', max_length=100)),
            ],
            options={
                'db_table': '请求记录表',
            },
        ),
    ]
