# Generated by Django 3.1.2 on 2021-05-25 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_requestlogtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogtable',
            name='requestTime',
            field=models.DateTimeField(db_column='请求时间', default=django.utils.timezone.now),
        ),
    ]
