# Generated by Django 3.1.2 on 2021-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210620_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(default='为自己打工的人儿~', max_length=20),
        ),
    ]
