# Generated by Django 3.1.2 on 2021-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_requestlogtable_requesttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogtable',
            name='path',
            field=models.CharField(db_column='路径', max_length=300),
        ),
    ]
