# Generated by Django 3.1.2 on 2021-05-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210525_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogtable',
            name='path',
            field=models.CharField(db_column='路径', max_length=500),
        ),
    ]
