# Generated by Django 3.1.2 on 2021-05-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210525_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlogtable',
            name='path',
        ),
    ]
