# Generated by Django 3.1.2 on 2021-05-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_requestlogtable_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogtable',
            name='processorIdentifier',
            field=models.CharField(db_column='处理器的配置信息', max_length=100),
        ),
    ]
