# Generated by Django 3.1.2 on 2021-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_blog_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, db_column='标题', max_length=50),
        ),
    ]
