# Generated by Django 3.1.2 on 2021-05-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210529_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlogtable',
            name='numberOfProcess',
        ),
        migrations.RemoveField(
            model_name='requestlogtable',
            name='processorArchitecture',
        ),
        migrations.RemoveField(
            model_name='requestlogtable',
            name='processorIdentifier',
        ),
        migrations.RemoveField(
            model_name='requestlogtable',
            name='userName',
        ),
    ]
