# Generated by Django 3.1.2 on 2021-05-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210531_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogtable',
            name='requestPath',
            field=models.CharField(db_column='请求路径', default='/', max_length=50),
        ),
    ]
