# Generated by Django 3.1.2 on 2021-06-04 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_requestlogtable_requestpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_column='关键字', max_length=100)),
                ('createdTime', models.DateTimeField(db_column='搜索的日期', default=django.utils.timezone.now)),
            ],
        ),
    ]
