# Generated by Django 3.1.2 on 2021-06-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_searchtable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchtable',
            table='搜索记录表',
        ),
    ]
