# Generated by Django 3.1.2 on 2021-06-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210604_1317'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='用户表',
        ),
    ]
