# Generated by Django 3.1.2 on 2021-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210604_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('updatedTime',)},
        ),
    ]
