# Generated by Django 3.1.2 on 2021-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210604_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updatedTime',
            field=models.DateTimeField(db_column='文章修改的时间'),
        ),
    ]
