# Generated by Django 3.1.2 on 2021-06-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210607_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlogtable',
            name='computerName',
        ),
        migrations.RemoveField(
            model_name='requestlogtable',
            name='userProfile',
        ),
    ]
