# Generated by Django 3.1.2 on 2021-06-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210611_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlogtable',
            name='oS',
        ),
    ]
