# Generated by Django 3.1.2 on 2021-06-17 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPenTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomPenContent', models.CharField(db_column='随笔的内容', max_length=300)),
                ('randomPenTime', models.DateField(auto_now=True, db_column='随笔的时间')),
                ('isShow', models.BooleanField(db_column='是否显示', default=1)),
                ('randomPenBlogId', models.ForeignKey(db_column='随笔的相关博客的id', on_delete=django.db.models.deletion.CASCADE, to='app.blog')),
                ('randomPenUserId', models.ForeignKey(db_column='随笔人的id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '随笔记录表',
            },
        ),
        migrations.CreateModel(
            name='JudgeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='评论内容', max_length=500)),
                ('judgeTime', models.DateTimeField()),
                ('isShow', models.BooleanField(db_column='是否显示', default=True)),
                ('judgeBlog', models.ForeignKey(db_column='评论的博客的id', on_delete=django.db.models.deletion.CASCADE, to='app.blog')),
                ('judger', models.ForeignKey(db_column='评论人的id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '评论表',
            },
        ),
        migrations.CreateModel(
            name='CollectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCollected', models.BooleanField(db_column='是否被收藏', default=0)),
                ('collectTime', models.DateField(auto_now=True, db_column='收藏日期')),
                ('blogId', models.ForeignKey(db_column='被收藏的博客的id', on_delete=django.db.models.deletion.CASCADE, to='app.blog')),
                ('collectorId', models.ForeignKey(db_column='收藏人的id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '收藏记录表',
            },
        ),
    ]
