# Generated by Django 3.1.2 on 2021-06-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningPlanet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='judgetable',
            table='评论表',
        ),
    ]
