# Generated by Django 3.1.2 on 2021-06-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_requestlogtable_requestpath'),
        ('learningPlanet', '0002_auto_20210602_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgetable',
            name='judgeBlogId',
            field=models.ForeignKey(db_column='评论的博客的id', default=1, on_delete=django.db.models.deletion.CASCADE, to='app.blog'),
            preserve_default=False,
        ),
    ]
