# Generated by Django 3.1.2 on 2021-06-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningPlanet', '0003_judgetable_judgeblogid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgetable',
            old_name='judgeBlogId',
            new_name='judgeBlog',
        ),
        migrations.RenameField(
            model_name='judgetable',
            old_name='judgerId',
            new_name='judger',
        ),
    ]
