# Generated by Django 3.1.2 on 2021-06-12 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_remove_requestlogtable_os'),
        ('learningPlanet', '0007_collecttable_iscollected'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPenTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomPenTime', models.DateField(auto_now=True, db_column='随笔的时间')),
                ('randomPenBlogId', models.ForeignKey(db_column='随笔的相关博客的id', on_delete=django.db.models.deletion.CASCADE, to='app.blog')),
                ('randomPenUserId', models.ForeignKey(db_column='随笔人的id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '随笔记录表',
            },
        ),
    ]
