# Generated by Django 3.1.2 on 2021-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningPlanet', '0008_randompentable'),
    ]

    operations = [
        migrations.AddField(
            model_name='randompentable',
            name='randomPenContent',
            field=models.CharField(db_column='随笔的内容', default=1, max_length=300),
            preserve_default=False,
        ),
    ]
